//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.14 at 04:19:23 PM GMT-04:00 
//


package rif.bld.totptp.parameters.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rif.bld.totptp.parameters.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rif.bld.totptp.parameters.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.ListConsFunc }
     * 
     */
    public RIFBLDToTPTPParameters.ListConsFunc createRIFBLDToTPTPParametersListConsFunc() {
        return new RIFBLDToTPTPParameters.ListConsFunc();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.MethodApplicationPredicate }
     * 
     */
    public RIFBLDToTPTPParameters.MethodApplicationPredicate createRIFBLDToTPTPParametersMethodApplicationPredicate() {
        return new RIFBLDToTPTPParameters.MethodApplicationPredicate();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.MemberPredicate }
     * 
     */
    public RIFBLDToTPTPParameters.MemberPredicate createRIFBLDToTPTPParametersMemberPredicate() {
        return new RIFBLDToTPTPParameters.MemberPredicate();
    }

    /**
     * Create an instance of {@link IRIToSymbols }
     * 
     */
    public IRIToSymbols createIRIToSymbols() {
        return new IRIToSymbols();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.DataDomainPredicate }
     * 
     */
    public RIFBLDToTPTPParameters.DataDomainPredicate createRIFBLDToTPTPParametersDataDomainPredicate() {
        return new RIFBLDToTPTPParameters.DataDomainPredicate();
    }

    /**
     * Create an instance of {@link SlottedFunctor }
     * 
     */
    public SlottedFunctor createSlottedFunctor() {
        return new SlottedFunctor();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.SubclassPredicate }
     * 
     */
    public RIFBLDToTPTPParameters.SubclassPredicate createRIFBLDToTPTPParametersSubclassPredicate() {
        return new RIFBLDToTPTPParameters.SubclassPredicate();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.EmptyListConstant }
     * 
     */
    public RIFBLDToTPTPParameters.EmptyListConstant createRIFBLDToTPTPParametersEmptyListConstant() {
        return new RIFBLDToTPTPParameters.EmptyListConstant();
    }

    /**
     * Create an instance of {@link Constant }
     * 
     */
    public Constant createConstant() {
        return new Constant();
    }

    /**
     * Create an instance of {@link OtherReservedSymbols }
     * 
     */
    public OtherReservedSymbols createOtherReservedSymbols() {
        return new OtherReservedSymbols();
    }

    /**
     * Create an instance of {@link PositionalFunctor }
     * 
     */
    public PositionalFunctor createPositionalFunctor() {
        return new PositionalFunctor();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.TypedLitFunc }
     * 
     */
    public RIFBLDToTPTPParameters.TypedLitFunc createRIFBLDToTPTPParametersTypedLitFunc() {
        return new RIFBLDToTPTPParameters.TypedLitFunc();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.StringLitWithLangFunc }
     * 
     */
    public RIFBLDToTPTPParameters.StringLitWithLangFunc createRIFBLDToTPTPParametersStringLitWithLangFunc() {
        return new RIFBLDToTPTPParameters.StringLitWithLangFunc();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.IntLitFunc }
     * 
     */
    public RIFBLDToTPTPParameters.IntLitFunc createRIFBLDToTPTPParametersIntLitFunc() {
        return new RIFBLDToTPTPParameters.IntLitFunc();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.StringLitNoLangFunc }
     * 
     */
    public RIFBLDToTPTPParameters.StringLitNoLangFunc createRIFBLDToTPTPParametersStringLitNoLangFunc() {
        return new RIFBLDToTPTPParameters.StringLitNoLangFunc();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters }
     * 
     */
    public RIFBLDToTPTPParameters createRIFBLDToTPTPParameters() {
        return new RIFBLDToTPTPParameters();
    }

    /**
     * Create an instance of {@link RIFBLDToTPTPParameters.EqualityPredicate }
     * 
     */
    public RIFBLDToTPTPParameters.EqualityPredicate createRIFBLDToTPTPParametersEqualityPredicate() {
        return new RIFBLDToTPTPParameters.EqualityPredicate();
    }

}
