#!/bin/bash

JAR="target/ruleml-api-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
echo "%============ PSOA Rule Base ====================="
cat %1
echo "%================================================="
echo "%============ PSOA Query Document ================"
cat %2
echo "%================================================="

echo "%================================================="
echo "%============ PSOA2TPTP Translation:=============="
java -jar -enableassertions $JAR -q %2 %1

vkernel <(java -jar -enableassertions $JAR -q %2 %1)
