//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.14 at 04:19:23 PM GMT-04:00 
//


package rif.bld.totptp.parameters.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{rif_bld_to_tptp_parameters}functor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IRI" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "functor"
})
@XmlRootElement(name = "IRIToSymbols")
public class IRIToSymbols {

    @XmlElements({
        @XmlElement(name = "constant", type = Constant.class),
        @XmlElement(name = "slotted_functor", type = SlottedFunctor.class),
        @XmlElement(name = "positional_functor", type = PositionalFunctor.class)
    })
    protected List<Object> functor;
    @XmlAttribute(name = "IRI", required = true)
    protected String iri;

    /**
     * Gets the value of the functor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the functor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunctor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Constant }
     * {@link SlottedFunctor }
     * {@link PositionalFunctor }
     * 
     * 
     */
    public List<Object> getFunctor() {
        if (functor == null) {
            functor = new ArrayList<Object>();
        }
        return this.functor;
    }

    /**
     * Gets the value of the iri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIRI() {
        return iri;
    }

    /**
     * Sets the value of the iri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIRI(String value) {
        this.iri = value;
    }

}
