//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.14 at 04:19:23 PM GMT-04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "rif_bld_to_tptp_parameters", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rif.bld.totptp.parameters.jaxb;
